function productionSub = importfileProductionsSub(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PRODUCTIONSUB1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  PRODUCTIONSUB1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  productionSub1 = importfile("C:\Users\mgkolias\Dropbox\DataMining COMP8118\datamining\productionSub.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Nov-2020 16:17:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["origin_region", "sctg3", "subtons", "subunits", "subvalue", "subavemiles"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
productionSub = readtable(filename, opts);

%% Convert to output type
productionSub = table2array(productionSub);
end